name: Banking CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check .

      - name: Run Pytest
        run: uv run python -m pytest